### ISSUE TITLE
High TVe value

### ISSUE THREAD

**Issue by rohan-tworks** [tworkshyd/DisplayBoard-MCU2#3]
Observation:
After running for a duration of ~2 min the display shows high TVe value.

Currently set values:
Set TV:400 Displayed TVe: 566 TVi: 413 --> imgA

The machine was then stopped and started again.

It showed similar values.

I then changed the Set TV to various values see if this was happening at other values.

Set TV:350 Displayed TVe:535 TVi:528
Set TV:500 Displayed TVe:627 TVi:528
Set TV:400 Displayed TVe:547 TVi:425

The machine was then rebooted and we performed a zero calibration

Set TV:400 Displayed TVe:566 TVi:401 -->imgB

Steps to reproduce:
- Turn on the machine
- Set TV to any value
- Start the machine
- Observe the status screen for a few minutes.

Attached Images for reference.
imgA
![imgA](https://user-images.githubusercontent.com/66057853/84763305-9c22f980-afe9-11ea-9550-b54a78d67a5f.jpeg)

imgB
![imgB](https://user-images.githubusercontent.com/66057853/84763232-7f86c180-afe9-11ea-924d-e537d3f4e2f5.jpeg)

Sensor mV screen
![sensormV](https://user-images.githubusercontent.com/66057853/84763456-d8eef080-afe9-11ea-862a-6408e3cd2e5f.PNG)

**Comment by anandpkishore** [comment]
SensorManager - 
 capture_sensor_data : not to stop and start timer , if we stop and start the timer immediately -  total acquisition time became bigger value and TVe ,TVi are impacted with lesser values
 remove logic to use 0.2 older pressure + 0.8 present pressure value for latest calculation
 store offset for calibration using long Param.

 Memory.c - 
retrieveCalibParamLong to store and retrieve long int values 

 ADC file 
 - read 1 sample instead of 3 and averaging it, so that we can read more samples per cycle

uploaded changes on dev branch
